config/routes.rb
Rails.application.routes.draw do
  resources :sprites
  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  resources :sheets
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/path.rb
class Path < ApplicationRecord
  belongs_to :sprite
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
  before_action :get_sprite
  before_action :set_path, only: %i[ show edit update destroy ]

  # GET /paths or /paths.json
  def index
    @paths = @sprite.paths
  end

  # GET /paths/1 or /paths/1.json
  def show
  end

  # GET /paths/new
  def new
    @path = @sprite.paths.build
  end

  # GET /paths/1/edit
  def edit
  end

  # POST /paths or /paths.json
  def create
    @path = @sprite.paths.build(path_params)

    respond_to do |format|
      if @path.save
        format.html { redirect_to sprite_paths_path(@sprite), notice: "Path was successfully created." }
        format.json { render :show, status: :created, location: @path }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paths/1 or /paths/1.json
  def update
    respond_to do |format|
      if @path.update(path_params)
        format.html { redirect_to sprite_path_path(@path), notice: "Path was successfully updated." }
        format.json { render :show, status: :ok, location: @path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paths/1 or /paths/1.json
  def destroy
    @path.destroy

    respond_to do |format|
      format.html { redirect_to sprite_paths_path(@sprite), notice: "Path was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def get_sprite
      @sprite = Sprite.find(params[:sprite_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_path
      @path = @sprite.paths.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def path_params
      params.require(:path).permit(:id_element, :class_element, :d_element, :sprite_id)
    end
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/views/paths/_form.html.erb
<%= form_with(model: [@sprite, path], local: true) do |form| %>
  <% if path.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(path.errors.count, "error") %> prohibited this path from being saved:</h2>

      <ul>
        <% path.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :id_element, class:"form-control", placeholder: "ID" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :class_element, class:"form-control", placeholder: "Class" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :d_element, class:"form-control", placeholder: "D" %>
  </div>
  <br/>

  <div>
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/paths/_path.html.erb
<div id="<%= dom_id path %>">
  <p>
    <strong>Id element:</strong>
    <%= path.id_element %>
  </p>

  <p>
    <strong>Class element:</strong>
    <%= path.class_element %>
  </p>

  <p>
    <strong>D element:</strong>
    <%= path.d_element %>
  </p>

  <p>
    <strong>Sprite:</strong>
    <%= path.sprite_id %>
  </p>

</div>

app/views/paths/edit.html.erb
<h1>Editing path</h1>

<%= render "form", path: @path %>

<br>

<div class="btn-toolbar">
  <div class="btn-group me-2">
    <%= link_to "Show", [@sprite, @path], class:"btn btn-secondary" %>
    <%= link_to "Back", sprite_paths_path(@sprite), class:"btn btn-dark" %>
  </div>
</div>

app/views/paths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paths</h1>

<table class="table table-striped table-hover">
  <thead class="table-secondary">
    <tr>
      <th>Id</th>
      <th>Class</th>
      <th>D</th>
      <th>Sprite</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paths.each do |path| %>
      <tr>
        <td><%= path.id_element %></td>
        <td><%= path.class_element %></td>
        <td><%= path.d_element %></td>
        <td><%= path.sprite.name %></td>
        <td><%= link_to 'Edit Path', edit_sprite_path_path(@sprite, path), class: "btn btn-dark" %></td>
        <td><%= button_to 'Destroy Path', [@sprite, path], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="btn-group me-2">
  <%= link_to 'New Path', new_sprite_path_path(@sprite), class: "btn btn-secondary" %>
  <td><%= link_to 'Show Sprite', [@sprite], class: "btn btn-dark" %></td>
</div>

app/views/paths/new.html.erb
<h1>New path</h1>

<%= render "form", path: @path %>

<br>

<div>
  <%= link_to "Back", sprite_paths_path(@sprite), class: "btn btn-secondary" %>
</div>

app/views/paths/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @path %>

<div class="btn-toolbar">
<div class="btn-group me-2">
  <td><%= link_to 'Edit Path', edit_sprite_path_path(@sprite), class: "btn btn-secondary" %></td>
  <%= link_to "Paths", sprite_paths_path(@sprite), class: "btn btn-dark" %>
  </div>
  <%= link_to "Back", sprite_path(@sprite), class: "btn btn-secondary" %>
</div>