config/routes.rb
Rails.application.routes.draw do
  resources :sprites
  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  resources :sheets
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/sheet.rb
class Sheet < ApplicationRecord
    belongs_to :user
    has_many :sprites
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_action :set_sheet, only: %i[ show edit update destroy ]

  # GET /sheets or /sheets.json
  def index
    @sheets = Sheet.all
  end

  # GET /sheets/1 or /sheets/1.json
  def show
  end

  # GET /sheets/new
  def new
    @sheet = Sheet.new
  end

  # GET /sheets/1/edit
  def edit
  end

  # POST /sheets or /sheets.json
  def create
    @sheet = Sheet.new(sheet_params)

    respond_to do |format|
      if @sheet.save
        format.html { redirect_to sheet_url(@sheet), notice: "Sheet was successfully created." }
        format.json { render :show, status: :created, location: @sheet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sheets/1 or /sheets/1.json
  def update
    respond_to do |format|
      if @sheet.update(sheet_params)
        format.html { redirect_to sheet_url(@sheet), notice: "Sheet was successfully updated." }
        format.json { render :show, status: :ok, location: @sheet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sheets/1 or /sheets/1.json
  def destroy
    @sheet.destroy

    respond_to do |format|
      format.html { redirect_to sheets_url, notice: "Sheet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sheet
      @sheet = Sheet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sheet_params
      params.require(:sheet).permit(:name, :frames, :rows, :columns, :reel_width, :reel_height, :sheet_size, :user_id)
    end
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/sheets/_form.html.erb
<%= form_with(model: sheet) do |form| %>
  <% if sheet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sheet.errors.count, "error") %> prohibited this sheet from being saved:</h2>

      <ul>
        <% sheet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field form-group">
    <%= form.text_field :sheet_name, class:"form-control", placeholder: "Name" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :frames, class:"form-control", placeholder: "Frames" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :rows, class:"form-control", placeholder: "Rows" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :columns, class:"form-control", placeholder: "Columns" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :reel_width, class:"form-control", placeholder: "Reel Width" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :reel_height, class:"form-control", placeholder: "Reel Height" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :sheet_size, class:"form-control", placeholder: "Sheet Size" %>
  </div>
  <br/>
  
  <div class="field form-group">
    <%= form.number_field :user_id, id: :sheet_user_id, class:"form-control", value: current_user.id, type: :hidden  %>
  </div>
  <br/>

  <div>
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/sheets/_sheet.html.erb
<div id="<%= dom_id sheet %>">
  <p>
    <strong>Sheet name:</strong>
    <%= sheet.name %>
  </p>

  <p>
    <strong>Frames:</strong>
    <%= sheet.frames %>
  </p>

  <p>
    <strong>Rows:</strong>
    <%= sheet.rows %>
  </p>

  <p>
    <strong>Columns:</strong>
    <%= sheet.columns %>
  </p>

  <p>
    <strong>Reel Width:</strong>
    <%= sheet.reel_width %>
  </p>

  <p>
    <strong>Reel Height:</strong>
    <%= sheet.reel_height %>
  </p>

  <p>
    <strong>Sheet Size:</strong>
    <%= sheet.sheet_size %>
  </p>

</div>

app/views/sheets/edit.html.erb
<h1>Editing sheet</h1>

<%= render "form", sheet: @sheet %>

<br>

<div class="btn-toolbar">
  <div class="btn-group me-2">
    <%= link_to "Show this sheet", @sheet, class:"btn btn-secondary" %>
    <%= link_to "Back to sheets", sheets_path, class:"btn btn-dark" %>
  </div>
</div>

app/views/sheets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sheets</h1>

<table class="table table-striped table-hover">
  <thead class="table-secondary">
    <th>Id</th>
    <th>Name</th>
    <th>Frames</th>
    <th>Rows</th>
    <th>Columns</th>  
    <th>Reel Width</th>
    <th>Reel Height</th>
    <th>Sheet Size</th>
    <th>Sprites</th>
    <th colspan='3'> </th>
  </thead>

  <tbody id="sheets">
  <% @sheets.each do |sheet| %>
      <tr>
        <td>
          <%= sheet.id %>
        <td>
          <%= sheet.name%>
        </td>
        <td>
          <%= sheet.frames%>
        </td>
        <td>
          <%= sheet.rows%>
        </td>
        <td>
          <%= sheet.columns%>
        </td>
        <td>
          <%= sheet.reel_width%>
        </td>
        <td>
          <%= sheet.reel_height%>
        </td>
        <td>
          <%= sheet.sheet_size%>
        </td>
        <td>
          <%= link_to "Sprites", sprites_path %>
        </td>
        <td>
          <%= link_to 'Show', sheet, class: "btn btn-secondary" %>
        </td>
        <td>
          <%= link_to 'Edit', edit_sheet_path(sheet), class: "btn btn-dark" %>
        </td>
        <td>
          <%= link_to 'Destroy', sheet, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
        </td>
      </tr>

  <% end %>
</table>

<%= link_to "New sheet", new_sheet_path, class: "btn btn-secondary"%>

app/views/sheets/new.html.erb
<h1>New sheet</h1>

<%= render "form", sheet: @sheet %>

<br>

<div>
  <%= link_to "Back to sheets", sheets_path %>
</div>

app/views/sheets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sheet %>


<div class="btn-group me-2">
  <%= link_to "Edit", edit_sheet_path(@sheet), class: "btn btn-secondary" %>
  <%= link_to "Back", sheets_path, class: "btn btn-dark" %>
</div>
<br/> 
<br/> 
<%= button_to "Destroy this sheet", @sheet, method: :delete, class: "btn btn-danger" %>