config/routes.rb
Rails.application.routes.draw do
  resources :sprites
  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  resources :sheets
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/sprite.rb
class Sprite < ApplicationRecord
    belongs_to :sheet
end

app/controllers/sprites_controller.rb
class SpritesController < ApplicationController
  before_action :set_sprite, only: %i[ show edit update destroy ]

  # GET /sprites or /sprites.json
  def index
    @sprites = Sprite.all
    @sheets = Sheet.all
  end

  # GET /sprites/1 or /sprites/1.json
  def show
  end

  # GET /sprites/new
  def new
    @sprite = Sprite.new
  end

  # GET /sprites/1/edit
  def edit
  end

  # POST /sprites or /sprites.json
  def create
    @sprite = Sprite.new(sprite_params)

    respond_to do |format|
      if @sprite.save
        format.html { redirect_to sprite_url(@sprite), notice: "Sprite was successfully created." }
        format.json { render :show, status: :created, location: @sprite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sprite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sprites/1 or /sprites/1.json
  def update
    respond_to do |format|
      if @sprite.update(sprite_params)
        format.html { redirect_to sprite_url(@sprite), notice: "Sprite was successfully updated." }
        format.json { render :show, status: :ok, location: @sprite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sprite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sprites/1 or /sprites/1.json
  def destroy
    @sprite.destroy

    respond_to do |format|
      format.html { redirect_to sprites_url, notice: "Sprite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sprite
      @sprite = Sprite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sprite_params
      params.require(:sprite).permit(:name, :frame, :row, :column, :width, :height, :viewbox, :sheet_id)
    end
end

app/helpers/sprites_helper.rb
module SpritesHelper
end

app/views/sprites/_form.html.erb
<%= form_with(model: sprite) do |form| %>
  <% if sprite.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sprite.errors.count, "error") %> prohibited this sprite from being saved:</h2>

      <ul>
        <% sprite.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :name, class:"form-control", placeholder: "Name" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :frame, class:"form-control", placeholder: "Frame" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :row, class:"form-control", placeholder: "Row" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :column, class:"form-control", placeholder: "Column" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :width, class:"form-control", placeholder: "Width" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :height, class:"form-control", placeholder: "Height" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :viewbox, class:"form-control", placeholder: "Viewbox" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :sheet_id, id: :sprite_sheet_id, class:"form-control", placeholder: "Sheet" %>
  </div>
  <br/>

  <div>
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/sprites/_sprite.html.erb
<div id="<%= dom_id sprite %>">
  <p>
    <strong>Name:</strong>
    <%= sprite.name %>
  </p>

  <p>
    <strong>Frame:</strong>
    <%= sprite.frame %>
  </p>

  <p>
    <strong>Row:</strong>
    <%= sprite.row %>
  </p>

  <p>
    <strong>Column:</strong>
    <%= sprite.column %>
  </p>

  <p>
    <strong>Width:</strong>
    <%= sprite.width %>
  </p>

  <p>
    <strong>Height:</strong>
    <%= sprite.height %>
  </p>

  <p>
    <strong>Viewbox:</strong>
    <%= sprite.viewbox %>
  </p>


</div>

app/views/sprites/edit.html.erb
<h1>Editing sprite</h1>

<%= render "form", sprite: @sprite %>

<br>

<div class="btn-toolbar">
  <div class="btn-group me-2">
    <%= link_to "Show this sprite", @sprite, class:"btn btn-secondary" %>
    <%= link_to "Back to sprites", sprites_path, class:"btn btn-dark" %>
  </div>
</div>

app/views/sprites/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sprites</h1>

<table class="table table-striped table-hover">
  <thead class="table-secondary">
    <th>Id</th>
    <th>Sheet Id</th>
    <th>Name</th>
    <th>Frame</th>
    <th>Row</th>
    <th>Column</th>  
    <th>Height</th>
    <th>Width</th>
    <th>Viewbox</th>
    <th>Paths</th>
    <th colspan='4'> </th>
  </thead>

  <tbody id="sprites">
    <% @sprites.each do |sprite| %>
        <tr>
          <td>
            <%= sprite.id %>
          </td>
          <td>
            <%= sprite.sheet_id %>
          </td>
          <td>
            <%= sprite.name%>
          </td>
          <td>
            <%= sprite.frame%>
          </td>
          <td>
            <%= sprite.row%>
          </td>
          <td>
            <%= sprite.column%>
          </td>
          <td>
            <%= sprite.height%>
          </td>
          <td>
            <%= sprite.width%>
          </td>
          <td>
            <%= sprite.viewbox%>
          </td>
          <td>
            <%= link_to 'Show', sprite, class: "btn btn-secondary" %>
          </td>
          <td>
            <%= link_to 'Edit', edit_sprite_path(sprite), class: "btn btn-dark" %>
          </td>
          <td>
            <%= link_to 'Destroy', sprite, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
          </td>
        </tr>

    <% end %>
  </table>

<%= link_to "New sprite", new_sprite_path, class: "btn btn-secondary"%>

<%#= @sheets.inspect
 %>

app/views/sprites/new.html.erb
<h1>New sprite</h1>

<%= render "form", sprite: @sprite %>

<br>

<div>
  <%= link_to "Back to sprites", sprites_path %>
</div>

app/views/sprites/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sprite %>

<div class="btn-toolbar">
  <%#= link_to 'Add Path', sprite_paths_path(@sprite), class: "btn btn-dark" %>
</div>
<br/>

<div class="btn-group me-2">
  <%= link_to "Edit", edit_sprite_path(@sprite), class: "btn btn-secondary" %>
  <%= link_to "Back", sprites_path, class: "btn btn-dark" %>
</div>
<br/>
<br/>
<div class="btn-group me-3">
  <%= button_to "Destroy this sprite", @sprite, method: :delete, class: "btn btn-danger" %>
</div>